### ISSUE TITLE
Configurable labels

### ISSUE THREAD

**Issue by mmkal** [alexleventer/github-issue-due-dates-action#70]
Would be nice if we could do something like this:

```yaml
name: Main Workflow
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.2.0
        with:
          labels:
            - days: 14
              label: 'Due in 2 weeks'
            - days: 28
              label: 'Due in 4 weeks'
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
```

Where the default value is 

```yaml
            - days: 7
              label: 'Due in 1 week'
```

To match the current behaviour.

**Comment by alexleventer** [comment]
Addressed in [v2.0.0](https://github.com/alexleventer/github-issue-due-dates-action/releases/tag/v2.0.0) via the new `upcoming-labels` input, which accepts exactly the YAML shape you proposed. Example:

```yaml
- uses: alexleventer/github-issue-due-dates-action@v2
  with:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    upcoming-labels: |
      - days: 14
        label: 'Due in 2 weeks'
      - days: 28
        label: 'Due in 4 weeks'
```

The default preserves the previous behavior (`days: 7, label: 'Due in 1 week'`). Smallest-matching bucket wins.

- Input definition: [`action.yml`](https://github.com/alexleventer/github-issue-due-dates-action/blob/master/action.yml)
- Parser: [`src/utils/labels.ts`](https://github.com/alexleventer/github-issue-due-dates-action/blob/master/src/utils/labels.ts)
- Selector + tests: [`src/processor.ts`](https://github.com/alexleventer/github-issue-due-dates-action/blob/master/src/processor.ts), [`__tests__/labels.test.ts`](https://github.com/alexleventer/github-issue-due-dates-action/blob/master/__tests__/labels.test.ts)

Thanks for the thoughtful issue — the proposed API shape landed as-is. Closing.
